#!/bin/bash

echo "🚀 Quick Deployment to Vercel"
echo ""
echo "📌 IMPORTANT: You'll need to:"
echo "1. Run: vercel"
echo "2. Answer the prompts (project name: muenchner-gastrotour)"
echo "3. Add domains in Vercel dashboard"
echo ""
echo "🔧 DNS Settings for your domain provider:"
echo ""
echo "For münchner-gastrotour.de:"
echo "  Type    Name    Value"
echo "  A       @       76.76.21.21"
echo "  CNAME   www     cname.vercel-dns.com"
echo ""
echo "For münchner-gastrotour.com:"
echo "  Type    Name    Value"
echo "  A       @       76.76.21.21"
echo "  CNAME   www     cname.vercel-dns.com"
echo ""
echo "📝 Environment variables to set in Vercel:"
echo "  - JWT_SECRET (generate a random string)"
echo "  - DATABASE_URL (use Vercel Postgres)"
echo "  - RESEND_API_KEY (if using email)"
echo "  - ADMIN_EMAIL"
echo ""
echo "Ready? Run: vercel"